# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb 4
def say_hello(to):
    "Say hello to some body"
    return f'Hello {to}'

# %% ../nbs/00_core.ipynb 11
def foo(): pass
